### ISSUE TITLE
Does Userhook-sdk-ios support the ipv6?

### ISSUE THREAD

**Issue by umtclskn** [cullaboration/userhook-sdk-ios#2]
Hi,
My iOS app was rejected, "Itunesconnect- Resolution Center" message is: Your app crashed on iPad running iOS 10.3.3 connected to an IPv6 network when we tapped on the button...
I'm using Userhook. I trigger an Userhook' event 3 minutes later when user open the app so i assume that the Userhook lib does not support ipv6.

I checked Userhook and userhook app link
( https://apps.userhook.com/pages )
from http://ipv6-test.com/validate.php this site. And it says link is not available on ipv6.

Does Userhook support the ipv6 networking?
Thanks.

**Comment by whynotmatt** [comment]
There are 2 issues here. First, the iOS SDK is suppose to fail silently (whether using ipv4 or ipv6) if it cannot connect to the User Hook servers. So if the crash was caused by a network issue, it would be helpful if you could provide us more information about that. 

Secondly, I did look over our ipv6 settings and I did make some adjustments on our servers. The domain that the SDK interacts with is https://api.userhook.com and it should be ipv6 compatible now.
